### PR TITLE
resolve_hostname function to resolve host:port pairs

### PR DESCRIPTION
**Pull request by Fedcomp**
I needed to resolve udp hostname (ip:port) manually, so i could send udp packets to hostnames specified from command line.

Is it good enough to merge in?

### CODE REVIEW

**Comment by sbstp** [comment]
Good addition. I can't believe that nobody had issues with the `resolve` function being clearly broken. I'm not 100% on the name of the new function, I'll take some time to think about it and then I'll release this in `0.4`. Since the `resolve` function was broken and nobody reported it, I'm guessing no one used it, so we might be able to break the API here and rename the functions to `resolve_ip` and `resolve_addr` and have a clean API.

**Comment by sbstp** [comment]
I've released this in `0.4.0`. I've renamed the functions a bit.

**Comment by Fedcomp** [comment]
Now when i think about it, often when we resolve hostnames we want to specify _default port_ (if one is absent). What you think about it?

Say i resolve example.com and i know http default port is 80, so i want to specify one in function if user did not provide it.

**Comment by sbstp** [comment]
That's probably outside the scope of this crate.

**Comment by Fedcomp** [comment]
tokio-dns helps reduce boilerplate when passing user hostname argument to tokio server/clients. Really often you want to have default port, it's nearly in every software. You say ftp://hostname and it substitute default port, same for www, same for many games.
Default port when one is absent sounds like good fit to me.

Otherwise you will end up writing all that boilerplate you wanted to avoid with tokio-dns.

**Comment by sbstp** [comment]
It does hostname resolution, it doesn't deal with protocols in any way. If you pass `ftp://google.com` or `http://google.com` it will fail. It doesn't know anything about URLs.

**Comment by Fedcomp** [comment]
No no no, just default port.
Say you can
```rust
// Will give us socket addr with default web port
tokio_dns::resolve_ip_addr_with_port("rust-lang.org", 80);
// Won't give us default port because user specified port explicitly
tokio_dns::resolve_ip_addr_with_port("rust-lang.org:443", 80);
```

this way i could do
```
mytelnet example.com
mytelnet example.com:443
```

**Pull request merged**
