### PR TITLE
Add explicit type annotations to fold (required with recent nightly compiler)

### PR DESCRIPTION
**Pull request by mehcode**

### CODE REVIEW

**Comment by sbstp** [comment]
Is the issue caused by a compiler bug or is it something that was unsound?

**Comment by sbstp** [comment]
Either way I'll merge this since it shouldn't have a negative impact going forward.

**Comment by sbstp** [comment]
Available in `0.3.1`.

**Comment by mehcode** [comment]
Thanks for the quick update. 

I didn't look into why it's causing an error now. Haven't had time. It won't matter in your case as soon we'll have std futures and the type changes to `Future<Output = T>`.

**Pull request merged**
